### ISSUE TITLE
Detecting wrong  sign

### ISSUE THREAD

**Issue by aakashkag** [purvanshi/isolvemath#5]
http://isolvemath.tech/irpredsuccess/1+1

I entered 1+1

it's is understanding 1-1, giving answer 0

**Comment by sidrocks123** [comment]
I think the main problem is that the project is a Math Word Problem Solver, not an arithmetic calculator. 

The input box on the site takes in a word problem as input, separates it into two parts (world state, which are the facts that are given, and the query state, which is the question asked), and builds a neural network model. This model is then used to solve the question.

Any problem like "1 + 1" may or may not work. 
EDIT : Just checked, the input "What is 1 + 1?" gives 2, and the input "What is 1 - 1?" also gives 2, since there is no data to extract (or work with) which leads to ambiguity.
